kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: nginx
  minReplicas: 1
  maxReplicas: 10
  TargetCPUUtilizationPercentage: 5
