
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: myrs1
spec: 
  replicas: 3
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      labels:
        type: webserver
    spec:
      containers:
      - name: c1
        image: httpd


