kind: Pod
apiVersion: v1
metadata:
  name: pod-pvc1
spec:
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc1
